### ISSUE TITLE
Is it possible to use a difference of distance CV with the ASM?

### ISSUE THREAD

**Issue by emccart3** [kzinovjev/string-amber#2]
Hello, I am interested in trying the ASM method for a reaction that involves CV's that are differences of distances. I see this is not an option for cvs.def. If I create the restraint file manually, will I be able to perform ASM simulations for this reaction? Thank you for your assistance!

**Comment by kzinovjev** [comment]
Hi Erika! 

Instead of using a linear combination of distances, just put each distance as a separate CV. Then, in a sense, the method will look for an optimal (non-linear) combination of those distances to describe the process. For example, take a look at the [tutorial](https://github.com/kzinovjev/string-amber/blob/master/tutorial.md). There, an SN2 reaction (which you would normally treat with an antisymmetric transfer coordinate) is described by providing both distances, among with other potentially relevant CVs.

For a more complex case, take a look at the [tutorial](https://carlosramosg.com/string-method) by Carlos Ramos. There, the reaction involves several proton transfers, each involving two CVs: donor-proton and acceptor-proton distances.

Regarding the "manual" restraints, you can use them, but they must be exactly the same for all the string nodes. So, they only make sense for the degrees of freedom that should not change during the reaction. This is because every string node should have exactly the same potential energy function, which is not the case when varying restraints are used (for example, as in Umbrella Sampling calculations).

**Comment by emccart3** [comment]
Thank you so much for the information!
